spring:
  data:
    mongodb:
      uri:  mongodb+srv://gauravdborhade:GAlb9BkCGLeBB6IB@cluster0.kisnrx7.mongodb.net/journaldb?retryWrites=true&w=majority
      database:  journaldb
      auto-index-creation:  true

server:
  port:  8081
  servlet:
    context-path: /journal


#  Application properties code
#    # MongoDB connection URI ? specify DB directly in the URI
#    spring.data.mongodb.uri=mongodb+srv://gauravdborhade:GAlb9BkCGLeBB6IB@cluster0.kisnrx7.mongodb.net/journaldb?retryWrites=true&w=majority
#
#    # Optional: If using above URI, this line is NOT required:
#    # spring.data.mongodb.database=journaldb
#
#    # Automatically create indexes (useful for repositories)
#    spring.data.mongodb.auto-index-creation=true
#
#    # Spring Boot server port
#    server.port=8080
